data_config:
  embed_dir: ./model_binaries
  data_dir: ./dataset
  precompute: true
trainer_config:
  max_epochs: 1000
  batch_size: 64
  data_loader_workers: 4
  grad_norm_clip: 1.0
  snapshot_path: s3://dl-training-snapshots/snapshot.pt
  save_every: 3
  log_every: 100
  use_amp: true
  bucket_name: dl-training-snapshots

optimizer_config:
  weight_decay: 0.01
  learning_rate: 0.001

mlflow:
  tracking_uri: databricks

hydra:
  run:
    dir: ./
