data_config:
  embed_dir: ./model_binaries
  data_dir: ./dataset
  precompute: true
trainer_config:
  max_epochs: 10
  batch_size: 128
  data_loader_workers: 4
  grad_norm_clip: 0.5
  snapshot_path: snapshot.pt
  save_every: 3
  log_every: 100
  use_amp: true
  bucket_name: dl-training-snapshots

optimizer_config:
  weight_decay: 0.01
  learning_rate: 0.0001

mlflow:
  tracking_uri: databricks

hydra:
  run:
    dir: ./
