data_config:
  embed_dir: ./model_binaries
  data_dir: ./dataset
  precompute: true
trainer_config:
  max_epochs: 10
  batch_size: 32 
  data_loader_workers:  0
  grad_norm_clip: 1.0
  snapshot_path: s3://dl-training-snapshots/snapshot.pt
  save_every: 1 
  log_every: 100
  use_amp: true
  bucket_name: dl-training-snapshots

optimizer_config:
  weight_decay: 0.0001
  learning_rate: 0.00003

mlflow:
  tracking_uri: databricks

hydra:
  run:
    dir: ./
